!["question"](question.jpg)



between layer 1 and 2:

$$
\begin{bmatrix}
  b_{10} & w_{11} & w_{21} \\
  b_{20} & w_{12} & w_{22} 
\end{bmatrix}
$$

where b = bias and w = weights

$x = [0.1,0.2]$

In [44]:
import numpy as np
from random import seed

In [120]:
x = np.array([[0.1,0.2],
      [0.3,0.8]]) # x1, x2

# x = [[0.1,0.2]]

input is columns, output is rows 

In [100]:
def Linear(num_nodes_input_layer, num_nodes_output_layer):
    """Dimensions: output is rows, input is columns."""
    seed(1)
    weights = np.random.rand(num_nodes_output_layer, num_nodes_input_layer + 1)
    # biases = np.ones((weights.shape[0], 1))

    # Stack the original array and the column of ones
    # return np.column_stack((biases, weights ))
    return weights


In [103]:
## define the layers
seed(1)
input = Linear(2,2)
seed(1)
hidden_layer1 = Linear(2,2)
seed(1)
output_layer = Linear(2,2)

hidden_layer1

array([[0.83057883, 0.44581712, 0.35657956],
       [0.09503414, 0.49783754, 0.6120248 ]])

In [104]:
def sigmoid(z):
    return np.array([1/(  1 + np.exp( -linear_combination )  ) for linear_combination in  z])

# Forward propogation to make predictions

!["how to apply the weights"](apply_weights.png)

$$ output = 
\begin{bmatrix}
  Neuron\:1\:applied\:to\:sample\:1 & Neuron\:2\:applied\:to\:sample\:1 \\
  Neuron\:1\:applied\:to\:sample\:2 & Neuron\:2\:applied\:to\:sample\:2
\end{bmatrix}
$$

In [160]:
def compute_forward(inputs, layer):
    ## linear combination w0x0 + w1x1 + w2x2
    linear_combinations = []

    inputs = np.c_[ np.ones(x.shape[1]), x  ]    ## add bias to the inputs
    # print(inputs)
    # print(layer)

    linear_combinations = np.matmul(inputs, layer.T)
    
    # print(linear_combinations)

    sigmoids = 1/(  1 + np.exp( -linear_combinations ) )## compute a
    # print(sigmoids)

    return sigmoids, linear_combinations

# Predict the Class

In [ ]:
def softmax(output_logits):
    """Compute the probability of a sample belonging to class 1 or 2"""
    probability = np.exp(output_logits.T)/np.sum(np.exp(output_logits), axis = 1)

    # print(np.exp(output_logits) ,np.sum(np.exp(output_logits), axis = 1))

    return probability.T

In [255]:
sigmoids2, a2 = compute_forward(x, input)

# sigmoids3, a3 = compute_forward(a2, hidden_layer1)

otuput_sigmoids, a_output = compute_forward(a2, hidden_layer1)


# otuput_sigmoids, a_output = compute_forward(a3, output_layer)

probability = softmax(a_output)
# signmoids, output

# Loss function

$$
 J(θ)= - \frac{1}{m} {\sum^m_{i=1}\sum^k_{k=1} [y^{(i)}_kln(\frac{1}{1+e^{xθ^T}})_k + (1-y^{(i)}_k)ln(1-(\frac{1}{1+e^{xθ^T}})_k)]} 
$$
$$
 = \frac{1}{m} {\sum^m_{i=1}\sum^k_{k=1} [y^{(i)}_kln(a^{(L)}_k + (1-y^{(i)}_k)ln(1-a^{(L)}_k)]}

$$


$$  
output\_sigmoids = 
\begin{bmatrix}
  Neuron\:1\:applied\:to\:sample\:1 & Neuron\:2\:applied\:to\:sample\:1 \\
  Neuron\:1\:applied\:to\:sample\:2 & Neuron\:2\:applied\:to\:sample\:2
\end{bmatrix}
$$

In [256]:
def binary_cross_entropy_loss(output_sigmoids, target):
    
    ## m is number of samples
    ## k is total number of output units

    log_sigmoids = np.log(output_sigmoids)
    y_times_log_sigmoids = np.matmul(log_sigmoids, target.T)
    
    one_minus_log_sigmoids = 1 - np.log(otuput_sigmoids)
    one_minus_y_times_log_sigmoids = np.matmul(one_minus_log_sigmoids, target.T)
    return (y_times_log_sigmoids + one_minus_y_times_log_sigmoids)/len(target)
    # for sample in target:
    #     for row in output_sigmoids:
            
    #         print(row, sample)
    #     print("_____________")




In [257]:
y = np.array([1,0])
binary_cross_entropy_loss(otuput_sigmoids, y)

array([0.5, 0.5])

In [ ]:
def compute_backpropogation(output_sigmoids):
    """"""
    partial_z_partial_theta = output_sigmoids
    partial_a_partial_z = output_sigmoids * (1-output_sigmoids)
    partial_j_partial_a = () 


In [ ]:
def forward(inputs):
    inputs = in

array([[0.13692008, 0.4647963 ],
       [0.65395656, 0.00602726]])

In [76]:
import torch
import torch.nn as nn
import torch.optim as optim

In [87]:
class ANN(nn.Module):
    def __init__(self):
        super().__init__()


        self.input = nn.Linear(2,2)
        self.hidden_layer1 = nn.Linear(2,2)
        self.output_layer = nn.Linear(2,2)

    def forward(self, x):
        x = self.input(x)
        x = torch.sigmoid(x)
        x = self.hidden_layer1(x)
        x = torch.sigmoid(x)
        x = self.output_layer(x)

        return x
    
model = ANN()

x_vec = torch.tensor( [0.1,0.2] )
target = torch.tensor([1.0, 2])

# ----- Forward Propagation -----
output = model(x_vec)

# ----- Compute Loss -----
criterion = nn.BCEWithLogitsLoss()
loss = criterion(output, target)

# ----- Backpropagation -----
optimizer = optim.SGD(model.parameters(), lr = 0.01)
optimizer.zero_grad() ## remove old gradients
loss.backward()
optimizer.step()



